theme: jekyll-theme-midnight
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: Grin wallet API tutorial
description: A basic introduction on how to properly communicate with the grin-wallet API
show_downloads: false
