theme: jekyll-theme-midnight
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: Grin wallet API tutorial
description: A introduction about the basis of proper communication with the grin-wallet API.
show_downloads: false
